#image: docker:latest
#services:
#  - docker:dind

stages:
  - style
  - test
  - deploy

pep8:
  stage: style
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python2.7

unittest-py27:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python2.7

unittest-py34:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python3/4

docker-deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - docker build -t cicd-demo .
    - docker run -d -p 5000:5000 cicd-demo
    - docker tag cicd-demo output
    - docker login -u wilsonloltl -p Vi26151851@
    - docker push wilsonloltl/docker_cicd_testing:output
  only:
    - master