#image: docker:latest
#services:
#  - docker:dind

stages:
  - build
  - test
  - deploy

buildtest-python:
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python2.7

unittest-py27:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python2.7

unittest-py34:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python3/4

docker-test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - docker build -t cicd-demo .
    - docker run -d -p cicd-demo .
  only:
    - master

docker-deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - docker login -u wilsonloltl -p Vi26151851@
    - docker build -t wilsonloltl/docker_cicd_testing:cicd-demo .
    - docker push wilsonloltl/docker_cicd_testing:cicd-demo
  only:
    - master