#image: docker:latest
#services:
#  - docker:dind

stages:
  - build
  - test
  - deploy

buildtest-python:
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt

unittest-py27:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt

unittest-py34:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    -python Main.py

docker-test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - docker login registry.gitlab.com -u wilsonlo1997@gmail.com -p Vi26151851@
    - docker build -t registry.gitlab.com/wilsonltl/pso2_keeper_backend .
    - docker run -d -p 8080:8080 registry.gitlab.com/wilsonltl/pso2_keeper_backend
  only:
    - master

docker-deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - docker login registry.gitlab.com -u wilsonlo1997@gmail.com -p Vi26151851@
    - docker build -t registry.gitlab.com/wilsonltl/pso2_keeper_backend .
    - docker push registry.gitlab.com/wilsonltl/pso2_keeper_backend
  only:
    - master