image: docker:latest
services:
  - docker:dind

stages:
  - style
  - test
  - deploy

pep8:
  stage: style
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python2.7

unittest-py27:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python2.7

unittest-py34:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  tags:
    - python3/4

docker-deploy:
  stage: deploy
  script:
    - docker build -t cicd-demo .
    - docker run -d -p 5000:5000 cicd-demo
  tags:
    - uat
  only:
    - master

#build:
#  stage: build
#  script:
#  - docker build -t cicd-demo .
#  tags:
#    - uat

#test:
#  stage: test
#  script:
#  - apt-get update -qy
#  - apt-get install -y python-dev python-pip
#  - pip install -r requirements.txt

#docker-deploy:
#  stage: docker-deploy
#  script:
##  - if [ $(docker ps -aq --filter name= cicd-demo) ]; then docker rm -f cicd-demo;fi
#  - docker run -d -p 5000:5000 cicd-demo
#  tags:
#    - uat